"""add_recovery_step_photo

Revision ID: 06a728fe2898
Revises: 425105c8f160
Create Date: 2026-05-23 01:18:32.580008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06a728fe2898'
down_revision: Union[str, None] = '425105c8f160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_step_photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recovery_step_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recovery_step_id'], ['recovery_step.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_step_photo_recovery_step_id'), 'recovery_step_photo', ['recovery_step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_step_photo_recovery_step_id'), table_name='recovery_step_photo')
    op.drop_table('recovery_step_photo')
    # ### end Alembic commands ###
