"""add_is_email_verified_and_verification_token_table

Revision ID: 26a19d7e0152
Revises: 06a728fe2898
Create Date: 2026-06-04 01:17:03.064997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26a19d7e0152'
down_revision: Union[str, None] = '06a728fe2898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_token_token'), 'email_verification_token', ['token'], unique=True)
    op.create_index(op.f('ix_email_verification_token_user_id'), 'email_verification_token', ['user_id'], unique=False)
    op.add_column('user', sa.Column('is_email_verified', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_email_verified')
    op.drop_index(op.f('ix_email_verification_token_user_id'), table_name='email_verification_token')
    op.drop_index(op.f('ix_email_verification_token_token'), table_name='email_verification_token')
    op.drop_table('email_verification_token')
    # ### end Alembic commands ###
