"""initial schema

Revision ID: 2cf7b187b825
Revises: 
Create Date: 2026-05-03 11:40:42.910788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2cf7b187b825'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('profile_image_url', sa.String(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_is_deleted'), 'user', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('plant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('health_status', sa.String(length=20), nullable=False),
    sa.Column('last_watered', sa.DateTime(timezone=True), nullable=True),
    sa.Column('icon_code_point', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_plant_created_by_user_id'), 'plant', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_plant_is_deleted'), 'plant', ['is_deleted'], unique=False)
    op.create_table('care_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_care_task_created_by_user_id'), 'care_task', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_care_task_done'), 'care_task', ['done'], unique=False)
    op.create_index(op.f('ix_care_task_is_deleted'), 'care_task', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_care_task_plant_id'), 'care_task', ['plant_id'], unique=False)
    op.create_table('reminder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('icon_code_point', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_reminder_created_by_user_id'), 'reminder', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_reminder_is_deleted'), 'reminder', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_reminder_plant_id'), 'reminder', ['plant_id'], unique=False)
    op.create_table('scan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('plant_name', sa.String(length=100), nullable=False),
    sa.Column('species', sa.String(length=100), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('is_healthy', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_scan_created_by_user_id'), 'scan', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_scan_is_deleted'), 'scan', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_scan_plant_id'), 'scan', ['plant_id'], unique=False)
    op.create_table('recovery_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.String(length=2000), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('started_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estimated_recovery', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('do_list', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dont_list', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signs_of_improvement', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_recovery_plan_created_by_user_id'), 'recovery_plan', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_recovery_plan_is_active'), 'recovery_plan', ['is_active'], unique=False)
    op.create_index(op.f('ix_recovery_plan_is_deleted'), 'recovery_plan', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_recovery_plan_plant_id'), 'recovery_plan', ['plant_id'], unique=False)
    op.create_index(op.f('ix_recovery_plan_scan_id'), 'recovery_plan', ['scan_id'], unique=False)
    op.create_table('recovery_step',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recovery_plan_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('icon_code_point', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recovery_plan_id'], ['recovery_plan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_recovery_step_recovery_plan_id'), 'recovery_step', ['recovery_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_step_recovery_plan_id'), table_name='recovery_step')
    op.drop_table('recovery_step')
    op.drop_index(op.f('ix_recovery_plan_scan_id'), table_name='recovery_plan')
    op.drop_index(op.f('ix_recovery_plan_plant_id'), table_name='recovery_plan')
    op.drop_index(op.f('ix_recovery_plan_is_deleted'), table_name='recovery_plan')
    op.drop_index(op.f('ix_recovery_plan_is_active'), table_name='recovery_plan')
    op.drop_index(op.f('ix_recovery_plan_created_by_user_id'), table_name='recovery_plan')
    op.drop_table('recovery_plan')
    op.drop_index(op.f('ix_scan_plant_id'), table_name='scan')
    op.drop_index(op.f('ix_scan_is_deleted'), table_name='scan')
    op.drop_index(op.f('ix_scan_created_by_user_id'), table_name='scan')
    op.drop_table('scan')
    op.drop_index(op.f('ix_reminder_plant_id'), table_name='reminder')
    op.drop_index(op.f('ix_reminder_is_deleted'), table_name='reminder')
    op.drop_index(op.f('ix_reminder_created_by_user_id'), table_name='reminder')
    op.drop_table('reminder')
    op.drop_index(op.f('ix_care_task_plant_id'), table_name='care_task')
    op.drop_index(op.f('ix_care_task_is_deleted'), table_name='care_task')
    op.drop_index(op.f('ix_care_task_done'), table_name='care_task')
    op.drop_index(op.f('ix_care_task_created_by_user_id'), table_name='care_task')
    op.drop_table('care_task')
    op.drop_index(op.f('ix_plant_is_deleted'), table_name='plant')
    op.drop_index(op.f('ix_plant_created_by_user_id'), table_name='plant')
    op.drop_table('plant')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_is_deleted'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
