"""add_sunlight_humidity_to_plant

Revision ID: 425105c8f160
Revises: e867397034da
Create Date: 2026-05-23 00:28:41.930128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '425105c8f160'
down_revision: Union[str, None] = 'e867397034da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('sunlight', sa.String(length=30), nullable=True))
    op.add_column('plant', sa.Column('humidity', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant', 'humidity')
    op.drop_column('plant', 'sunlight')
    # ### end Alembic commands ###
