"""add image_url to plant

Revision ID: e867397034da
Revises: 2cf7b187b825
Create Date: 2026-05-14 22:58:59.095170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e867397034da'
down_revision: Union[str, None] = '2cf7b187b825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plant', 'image_url')
    # ### end Alembic commands ###
