"""add reminder and care_task tables

Revision ID: 5e9ba9c16fa8
Revises: f47a54d672df
Create Date: 2026-04-17 02:25:08.167878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e9ba9c16fa8'
down_revision: Union[str, None] = 'f47a54d672df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_care_task_created_by_user_id'), 'care_task', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_care_task_done'), 'care_task', ['done'], unique=False)
    op.create_index(op.f('ix_care_task_is_deleted'), 'care_task', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_care_task_plant_id'), 'care_task', ['plant_id'], unique=False)
    op.create_table('reminder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('icon_code_point', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_reminder_created_by_user_id'), 'reminder', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_reminder_is_deleted'), 'reminder', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_reminder_plant_id'), 'reminder', ['plant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminder_plant_id'), table_name='reminder')
    op.drop_index(op.f('ix_reminder_is_deleted'), table_name='reminder')
    op.drop_index(op.f('ix_reminder_created_by_user_id'), table_name='reminder')
    op.drop_table('reminder')
    op.drop_index(op.f('ix_care_task_plant_id'), table_name='care_task')
    op.drop_index(op.f('ix_care_task_is_deleted'), table_name='care_task')
    op.drop_index(op.f('ix_care_task_done'), table_name='care_task')
    op.drop_index(op.f('ix_care_task_created_by_user_id'), table_name='care_task')
    op.drop_table('care_task')
    # ### end Alembic commands ###
