"""First Migration with PLANT, SCANS and RECOVERYSTEPS

Revision ID: f47a54d672df
Revises: c9ffe4eedb23
Create Date: 2026-04-16 22:09:17.362940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f47a54d672df'
down_revision: Union[str, None] = 'c9ffe4eedb23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
